import { GenerationJob } from './types';

export const INITIAL_GALLERY_ITEMS: GenerationJob[] = [
  {
    id: 'sample-video-1',
    modality: 'video',
    subMode: 't2v',
    model: 'wan-2.1-14b',
    prompt: 'Hyper-realistic cinematic slow-motion drone flyover of bioluminescent neon waterfalls cascading through ancient cybernetic crystalline caverns, 8k',
    negativePrompt: 'flicker, cartoon, blur, low resolution, bad geometry',
    status: 'completed',
    progress: 100,
    currentStep: 30,
    totalSteps: 30,
    seed: 8492048,
    width: 1280,
    height: 720,
    fps: 24,
    duration: 5,
    aspectRatio: '16:9',
    loras: [
      { id: 'cinematic-film', name: 'Cinematic 35mm Grain', triggerWord: 'cinematic 35mm', weight: 0.8, category: 'Aesthetic' }
    ],
    resultUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1280&q=80',
    createdAt: Date.now() - 1000 * 60 * 32,
    completedAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'sample-video-2',
    modality: 'video',
    subMode: 'i2v',
    model: 'wan-2.1-14b',
    prompt: 'Cyberpunk street racer in rain-drenched Neo-Tokyo speeding through neon traffic, camera tracking along side profile with anamorphic light streaks',
    negativePrompt: 'blurry edges, deformation, compression',
    status: 'completed',
    progress: 100,
    currentStep: 30,
    totalSteps: 30,
    seed: 4920194,
    width: 720,
    height: 1280,
    fps: 24,
    duration: 6,
    aspectRatio: '9:16',
    loras: [
      { id: 'cyberpunk-neon', name: 'Cyberpunk Neo-Tokyo', triggerWord: 'neon glowing cyberpunk', weight: 0.85, category: 'Style' }
    ],
    resultUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=720&q=80',
    createdAt: Date.now() - 1000 * 60 * 55,
    completedAt: Date.now() - 1000 * 60 * 52,
  },
  {
    id: 'sample-video-3',
    modality: 'video',
    subMode: 't2v',
    model: 'hunyuan-video-1.5',
    prompt: 'Cosmic nebula blossoming into a celestial phoenix made of stardust and solar flares, fluid orbital camera glide, IMAX scale',
    negativePrompt: 'low dynamic range, jitter',
    status: 'completed',
    progress: 100,
    currentStep: 35,
    totalSteps: 35,
    seed: 1102948,
    width: 1280,
    height: 720,
    fps: 24,
    duration: 5,
    aspectRatio: '16:9',
    loras: [],
    resultUrl: 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1280&q=80',
    createdAt: Date.now() - 1000 * 60 * 120,
    completedAt: Date.now() - 1000 * 60 * 115,
  },
  {
    id: 'sample-image-1',
    modality: 'image',
    subMode: 't2i',
    model: 'flux-1-dev',
    prompt: 'Intricate macro portrait of an ethereal android with porcelain skin, glowing sapphire fiber-optic eyes, and delicate golden filigree circuits',
    negativePrompt: 'plastic, flat, cartoon, bad proportions',
    status: 'completed',
    progress: 100,
    currentStep: 28,
    totalSteps: 28,
    seed: 3948172,
    width: 1024,
    height: 1024,
    aspectRatio: '1:1',
    loras: [
      { id: 'photoreal-portrait', name: 'Raw Candid Photorealism', triggerWord: 'raw candid realistic shot', weight: 0.9, category: 'Realism' }
    ],
    resultUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1024&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1024&q=80',
    createdAt: Date.now() - 1000 * 60 * 180,
    completedAt: Date.now() - 1000 * 60 * 179,
  },
  {
    id: 'sample-image-2',
    modality: 'image',
    subMode: 't2i',
    model: 'flux-1-schnell',
    prompt: 'Surreal levitating island with Japanese cherry blossom trees, cascading glass water bridges, overlooking twilight mountains in fog',
    negativePrompt: 'dull, blurry, grainy',
    status: 'completed',
    progress: 100,
    currentStep: 4,
    totalSteps: 4,
    seed: 7829103,
    width: 1280,
    height: 720,
    aspectRatio: '16:9',
    loras: [],
    resultUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1280&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1280&q=80',
    createdAt: Date.now() - 1000 * 60 * 240,
    completedAt: Date.now() - 1000 * 60 * 239,
  }
];
